"""empty message

Revision ID: 717618702adf
Revises: 3c7b619c8eda
Create Date: 2023-03-20 21:52:35.173777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717618702adf'
down_revision = '3c7b619c8eda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
